# Generated by Django 5.0 on 2024-04-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requestbook',
        ),
    ]
